const msgs = {
  getBook: "Book - GET Request Success",
  getAllBooks: "Books - GET Request Success",
  getBookIds: "Books IDs and Titles Success",
  booksFound: "Books Found - GET Request Success",
  noBook: "No Book Found - GET Request Failure",
  noBooks: "No Books Found - GET Request Failure",
  bookCreated: "Books Created - POST Request Success",
  bookExists: "A Similar Book Already Exists in Catalogue",
  noBookCreated: "No Book Created - POST Request Failure",
  bookUpdated: "Book Updated - PUT Request Success",
  bookDeleted: "Book Deleted - DELETE Request Success",
  noAuthors: "No Authors Found - GET Request Failure",
  getAllAuthors: "Authors Found - GET Request Success",
  noAuthor: "No Author Found - GET Request Failure",
  getAuthor: "Author Found - GET Request Success",
  noAuthorCreated: "No Author Created - POST Request Failure",
  authorCreate: "Author Created - POST Request Success",
  authorUpdated: "Author Updated Successfully",
  authorUpdateFailed: "Author Could not be Updated",
  authorDeleted: "Author Deleted Successfully",
  authorDeletionFailed: "Could not DELETE author",
  emailRegisterFail:
    "Registration Failed. Please provide a valid email address",
  emailExists: "Email already registered, Try login",
  registrationSuccess: "Registration Successful",
  loginSuccess: "Login Successful",
  loginToAccess: "You must be log in to access this page",
  noLongerUser: "User No Longer Exists",
  userLoginFail: "User Authentication Failed: Unable to find user",
  authFail: "Authentication Failed",
  invalidLogin: "Invalid Login",
  noUser: "No User Found",
  userFound: "User Found - GET SUCCESS",
  noUsers: "No Users Found",
  usersFound: "Users Found - GET SUCCESS",
};

export default msgs;
